//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DebugEntitiesFails : DbContext
    {
        public DebugEntitiesFails()
            : base("name=DebugEntitiesFails")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<TestPrints_Result> TestPrints()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TestPrints_Result>("TestPrints");
        }
    }
}
